#!/usr/bin/env python3
"""Re-derive the fixture of the search suite's case "a reduced move that beats
alpha is searched again" -- the position it drives and the depth it drives at.

    python3 adocs/data/S231_research_witness.py \
        --positions adocs/data/S024_census_positions.txt --lo 4 --hi 8

WHY THIS EXISTS. That case pins a position and a depth and asserts that at
least one reduced move came back worth more than the ordering thought. Both are
a **measurement** and neither is a property of the position: the case's own
comment says the fixture "was found by scanning the 400 committed census
positions rather than picked", and it replaced perft position 2 at S109 for
exactly this reason -- the shallow-depth pruning block had made the old fixture
read `researched` 0 at every depth from 4 to 8. So a change to move ordering,
reduction or pruning can empty it again, which is what S231's two-ply
continuation table did to depth 6 of the position S109 chose. DEC-142 requires
a golden of this class to name the script that re-derives it and to be
re-derived by that script whenever either end moves; the case named the scan
and no script existed, and this is that script.

THE RULE, applied mechanically rather than by eye and stated before the sweep
so that it cannot be chosen after it:

  1. Keep the case's current position if it still re-searches somewhere in the
     swept range, and take the **lowest** such depth.
  2. Otherwise take the first position of the corpus, in the corpus's own
     order, that re-searches at every depth of the swept range -- which is the
     property S109's comment claims for its own fixture -- and its lowest
     depth.

Reporting `reduced` beside `researched` at every depth is what keeps the case's
own precondition honest: a depth where nothing was reduced is a depth where the
re-search rule decided nothing, and a fixture chosen there would assert over an
empty set.

THE DRIVE IS THE CASE'S DRIVE. `negamax_probed` at ply 1 with `alpha` -30000,
`beta` 30000, no previous move and no move two plies back, `is_pv` true --
line for line what the case does, including the wide window (so the loop keeps
running past the first move that beats alpha) and the PV node (so the
shallow-depth block does not remove the late quiets the case is about). A
throwaway driver compiled against the engine library **as it stands**, for
S230_mine_r01_row.py's own reason: the case calls the search directly from a
cold table and `go depth N` is iterative deepening over a warm one.

WHERE THE POSITIONS COME FROM. `adocs/data/S024_census_positions.txt`, this
project's own self-play sampled at S024 -- 400 positions, one per game, from
`adocs/data/S219_aa_calibration.pgn`. No other engine's positions and no
published set (DEC-016).
"""
import argparse
import os
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

DRIVER = r"""
// Generated by adocs/data/S231_research_witness.py. The drive of
// tests/test_search.cpp "a reduced move that beats alpha is searched again",
// line for line, over a list of FENs and a depth range.
#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>
#include <vector>
#include "bitboard.hpp"
#include "data_structures.hpp"
#include "search.hpp"
#include "transposition_table.hpp"

namespace
{
game_t game;
transposition_table_t tt;
std::atomic_bool never_stop = false;

// The case's own two numbers at one depth: how many moves this node reduced,
// and how many of those came back worth a second search.
void drive(const std::string& fen, int depth, size_t* reduced, size_t* again)
{
  if (!load_FEN(fen, &game)) {
    fprintf(stderr, "bad FEN: %s\n", fen.c_str());
    exit(2);
  }

  never_stop = false;
  tt_reset(&tt);
  tt_new_search(&tt);

  search_state_t state = {};
  state.tt = &tt;
  state.stop = &never_stop;

  search_node_probe_t probe = {};
  probe.ply = 1;
  state.probe = &probe;

  negamax_probed(-30000, 30000, depth, 1, &game, &state, 0, true);

  *reduced = 0;
  *again = 0;
  for (int i = 0; i < probe.move_count; ++i) {
    if (probe.reduction[i] <= 0) { continue; }
    (*reduced)++;
    if (probe.researched[i]) { (*again)++; }
  }
}
}  // namespace

int main(int argc, char** argv)
{
  if (argc != 4) { return 2; }
  const int lo = atoi(argv[2]);
  const int hi = atoi(argv[3]);

  std::vector<std::string> fens;
  std::ifstream handle(argv[1]);
  std::string line;
  while (std::getline(handle, line)) {
    if (line.empty() || line[0] == '#') { continue; }
    // The census file is "game_index<TAB>ply<TAB>fen"; a bare FEN list works
    // too, so the FEN is whatever follows the last tab.
    const size_t tab = line.rfind('\t');
    fens.push_back(tab == std::string::npos ? line : line.substr(tab + 1));
  }

  initialize_game_const_data(&game);
  tt_resize(&tt, 4);
  tt_reset(&tt);

  for (const std::string& fen : fens) {
    for (int depth = lo; depth <= hi; ++depth) {
      size_t reduced = 0;
      size_t again = 0;
      drive(fen, depth, &reduced, &again);
      printf("%zu/%zu ", reduced, again);
      fflush(stdout);
    }
    printf("\t%s\n", fen.c_str());
    fflush(stdout);
  }
  return 0;
}
"""


def sweep(positions, lo, hi, lib, out):
    work = tempfile.mkdtemp(prefix="s231_")
    source = os.path.join(work, "driver.cpp")
    binary = os.path.join(work, "driver")
    with open(source, "w") as handle:
        handle.write(DRIVER)

    build = subprocess.run(
        ["c++", "-I", os.path.join(REPO, "src"), "-O3", "-DNDEBUG",
         "-std=gnu++20", "-march=native", "-o", binary, source,
         os.path.join(REPO, lib)],
        capture_output=True, text=True)
    if build.returncode != 0:
        sys.stderr.write(build.stderr)
        return None

    run = subprocess.run([binary, positions, str(lo), str(hi)],
                         capture_output=True, text=True)
    sys.stderr.write(run.stderr)
    if run.returncode != 0:
        return None

    if out:
        with open(out, "w") as handle:
            handle.write(run.stdout)
    return run.stdout


def read_sweep(text, lo):
    rows = []
    for line in text.splitlines():
        if "\t" not in line:
            continue
        cells, fen = line.split("\t", 1)
        per_depth = {}
        for i, cell in enumerate(cells.split()):
            reduced, again = cell.split("/")
            per_depth[lo + i] = (int(reduced), int(again))
        rows.append((fen, per_depth))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--positions",
                    default="adocs/data/S024_census_positions.txt")
    ap.add_argument("--lo", type=int, default=4)
    ap.add_argument("--hi", type=int, default=8)
    ap.add_argument("--lib", default="build/src/libchesso_engine.a")
    ap.add_argument("--out", default=None)
    ap.add_argument("--current", default=None,
                    help="the FEN the case pins today; rule 1 applies to it")
    args = ap.parse_args()

    text = sweep(os.path.join(REPO, args.positions), args.lo, args.hi,
                 args.lib, args.out)
    if text is None:
        print("S231-WITNESS-FAILED")
        return 1

    rows = read_sweep(text, args.lo)

    if args.current:
        for fen, per_depth in rows:
            if fen != args.current:
                continue
            print("the pinned position: " + fen)
            for depth in sorted(per_depth):
                reduced, again = per_depth[depth]
                print("  depth %d: reduced %d researched %d"
                      % (depth, reduced, again))
            hits = [d for d in sorted(per_depth) if per_depth[d][1] > 0]
            if hits:
                print("RULE 1: keep the position, depth %d" % hits[0])
                print("S231-WITNESS-DONE")
                return 0
            print("RULE 1 does not apply: no depth in %d..%d re-searches"
                  % (args.lo, args.hi))
            break

    for fen, per_depth in rows:
        depths = sorted(per_depth)
        if all(per_depth[d][1] > 0 for d in depths):
            print("RULE 2: %s" % fen)
            for depth in depths:
                reduced, again = per_depth[depth]
                print("  depth %d: reduced %d researched %d"
                      % (depth, reduced, again))
            print("RULE 2: take depth %d" % depths[0])
            print("S231-WITNESS-DONE")
            return 0

    print("no position in %s re-searches at every depth %d..%d"
          % (args.positions, args.lo, args.hi))
    print("S231-WITNESS-DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
