// What the tuning corpus actually contains, per evaluation feature. S100.
//
//   build/tools/feature_audit --data .tuning/selfplay_v2_dedup.tsv
//
// S100 is a diagnosis: bishop pair, rook on an open file, rook on a half-open
// file, rook on the seventh and tempo all ship at zero, and passed_pawn_mg[5]
// fits below the bucket beneath it. Five terms at exactly zero is a pattern
// rather than five results, and four causes can produce it -- a feature
// extracted wrongly, a corpus that cannot discriminate the feature, a
// measurement procedure that could not resolve the effect, or a real zero. This
// tool answers the corpus half of that. It decides nothing on its own; what it
// produces is evidence for the ledger in the step file.
//
// Four reports and one writer, all off the same load:
//
//   columns      every stored column against the same feature recomputed from
//                the FEN text, over the whole corpus. It calls the same
//                extractors load() calls, so it is not a check of what a
//                feature *means* -- tests/test_eval_model.cpp holds those,
//                against the engine's counts and against placements worked out
//                by hand. What it catches is everything between a correct
//                extractor and a fitted weight: a misaligned base, a wrong
//                stride, a column pair stored in the other order.
//
//   identities   two claims that are exact by construction, checked on every
//                row rather than argued. Index 0 is a8 and a black piece is
//                mirrored by xor 56, so a rook on its own seventh rank always
//                lands on one of squares 8..15: the rook-on-the-seventh column
//                is *identically* the signed sum of eight rook piece-square
//                columns. And a pawn on its own seventh rank is a passer by
//                definition, because "ahead" is the enemy back rank and the
//                extractor refuses a pawn standing there, so passer bucket 5 is
//                identically the signed sum of eight pawn piece-square columns.
//                Two exact linear dependencies among the parameters, which is a
//                thing a joint fit cannot resolve and an --only fit resolves
//                only against the frozen table.
//
//   occurrence   how often each column is non-zero, whole corpus and by phase
//                band. The coverage form of the corpus hypothesis: a column
//                that is almost never non-zero has almost no signal to fit.
//                Split by phase because a column can be well covered overall
//                and empty in the band whose weight it is -- S065's
//                queens-under-phase-4 story, and the reason four positions had
//                to be added to tests/test_eval_positions.hpp at S100.
//
//   collinearity R^2 of each term column regressed on the piece-square columns
//                it overlaps. The correlation form of the same hypothesis, and
//                the one counting cannot answer. Above 0.99 the column carries
//                almost nothing the tables do not already carry, and a fit
//                returning zero for it is what a *correct* pipeline does. The
//                two exact identities above should come back at exactly 1.0,
//                which is this report checking itself.
//
//   --plant      writes a copy of the corpus with the result column replaced by
//                sigmoid(K * model_score) at planted, non-zero term weights.
//                The labels are then generated by a known parameter vector, so
//                a fit that cannot recover it has a defect and a fit that can
//                has its pipeline vouched for end to end. Every number planted
//                is written here and derived from nothing outside this
//                repository.
#include <algorithm>
#include <cinttypes>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include "eval_model.hpp"
#include "tuner_model.hpp"
#include "tuner_target.hpp"

namespace
{

using eval_model::KING_SAFETY_COUNT;
using eval_model::MG_BASE;
using eval_model::MOBILITY_COUNT;
using eval_model::PARAM_COUNT;
using eval_model::PASSED_PAWN_COUNT;
using eval_model::PAWN_STRUCTURE_COUNT;
using eval_model::PIECE_PLACEMENT_COUNT;
using eval_model::PL_BISHOP_PAIR;
using eval_model::PL_EG_BASE;
using eval_model::PL_MG_BASE;
using eval_model::PL_ROOK_HALF_OPEN;
using eval_model::PL_ROOK_OPEN;
using eval_model::PL_ROOK_SEVENTH;
using eval_model::PP_EG_BASE;
using eval_model::PP_MG_BASE;
using eval_model::TEMPO_EG_BASE;
using eval_model::TEMPO_MG_BASE;

// The piece types as eval_model codes them: square / 64 of a piece code.
constexpr size_t PAWN_TYPE = 0;
constexpr size_t BISHOP_TYPE = 2;
constexpr size_t ROOK_TYPE = 3;

// A rook or a pawn on its own seventh rank, in the mirrored indexing every
// piece code already uses. Row 0 is the enemy back rank and row 1 is the
// seventh, for both colours, because a black piece is mirrored by xor 56.
constexpr size_t SEVENTH_FIRST = 8;
constexpr size_t SEVENTH_LAST = 15;


struct options_t
{
  std::string data;
  std::string plant;
  std::string plant_group = "all";
  double plant_k =
      0.7624;  // S065's fitted K over this corpus, printed by that run
  size_t sample = 200000;  // rows the regression uses; every row for the rest
  bool columns = true;
  bool identities = true;
  bool occurrence = true;
  bool collinearity = true;
};


// The signed occupancy of one piece-square column: +1 for a White piece there,
// -1 for a Black one, which is exactly the coefficient that column carries in
// the linear model. Read off the piece list rather than recomputed from the
// FEN, because the piece list is what the fit reads.
struct occupancy_t
{
  std::vector<int8_t> value;  // 64 per row, one piece type
};


occupancy_t occupancy_of_type(const tuner_model::dataset_t& data,
                              size_t type,
                              const std::vector<uint32_t>& rows)
{
  occupancy_t out;
  out.value.assign(rows.size() * 64, 0);

  for (size_t r = 0; r < rows.size(); ++r) {
    const size_t row = rows[r];

    for (uint32_t j = data.offsets[row]; j < data.offsets[row + 1]; ++j) {
      const uint16_t code = data.pieces[j];
      const int sign = (code & eval_model::BLACK_BIT) ? -1 : 1;
      const size_t square = code & ~eval_model::BLACK_BIT;

      if (square / 64 != type) { continue; }

      out.value[r * 64 + (square % 64)] += static_cast<int8_t>(sign);
    }
  }

  return out;
}


// Ordinary least squares of `y` on `columns` plus an intercept, by normal
// equations, returning R^2. The design is at most 65 wide and the entries are
// in -1..1, so a Cholesky on the Gram matrix is enough; a column that is
// constant over the sample makes the matrix singular and is dropped rather than
// pivoted, since a column nothing varies explains nothing.
double r_squared(const std::vector<double>& y,
                 const std::vector<std::vector<double>>& columns)
{
  const size_t n = y.size();
  if (n == 0) { return 0.0; }

  std::vector<const std::vector<double>*> keep;
  for (const std::vector<double>& column : columns) {
    double lo = column[0];
    double hi = column[0];

    for (const double value : column) {
      lo = std::min(lo, value);
      hi = std::max(hi, value);
    }

    if (hi > lo) { keep.push_back(&column); }
  }

  const size_t width = keep.size() + 1;  // + intercept
  std::vector<double> gram(width * width, 0.0);
  std::vector<double> rhs(width, 0.0);

  for (size_t i = 0; i < n; ++i) {
    std::vector<double> row(width);
    row[0] = 1.0;
    for (size_t c = 0; c < keep.size(); ++c) {
      row[c + 1] = (*keep[c])[i];
    }

    for (size_t a = 0; a < width; ++a) {
      rhs[a] += row[a] * y[i];
      for (size_t b = 0; b < width; ++b) {
        gram[a * width + b] += row[a] * row[b];
      }
    }
  }

  // Ridge of 1e-9 on the diagonal: the design has exactly collinear columns by
  // construction here -- that is the thing being measured -- and a bare
  // Cholesky on a singular Gram matrix fails rather than returning the fit that
  // exists.
  for (size_t a = 0; a < width; ++a) {
    gram[a * width + a] += 1e-9;
  }

  // Cholesky, in place.
  for (size_t a = 0; a < width; ++a) {
    for (size_t b = 0; b <= a; ++b) {
      double sum = gram[a * width + b];

      for (size_t c = 0; c < b; ++c) {
        sum -= gram[a * width + c] * gram[b * width + c];
      }

      if (a == b) {
        if (sum <= 0.0) { return -1.0; }
        gram[a * width + a] = std::sqrt(sum);
      } else {
        gram[a * width + b] = sum / gram[b * width + b];
      }
    }
  }

  std::vector<double> beta(width, 0.0);
  for (size_t a = 0; a < width; ++a) {
    double sum = rhs[a];
    for (size_t c = 0; c < a; ++c) {
      sum -= gram[a * width + c] * beta[c];
    }
    beta[a] = sum / gram[a * width + a];
  }
  for (size_t a = width; a-- > 0;) {
    double sum = beta[a];
    for (size_t c = a + 1; c < width; ++c) {
      sum -= gram[c * width + a] * beta[c];
    }
    beta[a] = sum / gram[a * width + a];
  }

  double mean = 0.0;
  for (const double value : y) {
    mean += value;
  }
  mean /= static_cast<double>(n);

  double residual = 0.0;
  double total = 0.0;

  for (size_t i = 0; i < n; ++i) {
    double predicted = beta[0];
    for (size_t c = 0; c < keep.size(); ++c) {
      predicted += beta[c + 1] * (*keep[c])[i];
    }

    residual += (y[i] - predicted) * (y[i] - predicted);
    total += (y[i] - mean) * (y[i] - mean);
  }

  if (total <= 0.0) { return -1.0; }

  return 1.0 - residual / total;
}


void usage()
{
  printf(
      "usage: feature_audit --data FILE [--plant FILE] [--plant-k K]\n"
      "                     [--plant-group "
      "all|passed_pawns|piece_placement|tempo]\n"
      "                     [--sample N] [--no-columns] [--no-identities]\n"
      "                     [--no-occurrence] [--no-collinearity]\n");
}

}  // namespace


int main(int argc, char** argv)
{
  options_t opts;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    const bool has_value = (i + 1 < argc);

    if (arg == "--data" && has_value) {
      opts.data = argv[++i];
    } else if (arg == "--plant" && has_value) {
      opts.plant = argv[++i];
    } else if (arg == "--plant-group" && has_value) {
      opts.plant_group = argv[++i];
    } else if (arg == "--plant-k" && has_value) {
      opts.plant_k = atof(argv[++i]);
    } else if (arg == "--sample" && has_value) {
      opts.sample = static_cast<size_t>(atoll(argv[++i]));
    } else if (arg == "--no-columns") {
      opts.columns = false;
    } else if (arg == "--no-identities") {
      opts.identities = false;
    } else if (arg == "--no-occurrence") {
      opts.occurrence = false;
    } else if (arg == "--no-collinearity") {
      opts.collinearity = false;
    } else {
      usage();
      return 1;
    }
  }

  if (opts.data.empty()) {
    usage();
    return 1;
  }

  tuner_model::dataset_t data;

  if (!tuner_model::load(opts.data, &data)) {
    fprintf(stderr, "could not load %s\n", opts.data.c_str());
    return 1;
  }

  printf("corpus %s, %zu rows\n", opts.data.c_str(), data.size());

  // --------------------------------------------------------------- columns
  //
  // The FEN text has to be read a second time for this, because load() keeps
  // the piece list and not the string it came from.
  if (opts.columns) {
    std::ifstream file(opts.data);
    std::string line;
    size_t row = 0;
    size_t disagreements = 0;

    while (std::getline(file, line)) {
      if (line.empty()) { continue; }

      std::istringstream fields(line);
      std::string fen;
      if (!std::getline(fields, fen, '\t')) { continue; }

      std::istringstream fen_fields(fen);
      std::string placement, side_to_move;
      fen_fields >> placement;
      fen_fields >> side_to_move;

      int mobility[MOBILITY_COUNT] = {};
      int safety[KING_SAFETY_COUNT] = {};
      int passed[PASSED_PAWN_COUNT] = {};
      int structure[PAWN_STRUCTURE_COUNT] = {};
      int placement_counts[PIECE_PLACEMENT_COUNT] = {};
      int tempo = 0;

      eval_model::mobility_features(placement, mobility);
      eval_model::king_safety_features(placement, safety);
      eval_model::passed_pawn_features(placement, passed);
      eval_model::pawn_structure_features(placement, structure);
      eval_model::piece_placement_features(placement, placement_counts);
      eval_model::tempo_feature(side_to_move, &tempo);

      for (size_t i = 0; i < MOBILITY_COUNT; ++i) {
        if (data.mobility[row * MOBILITY_COUNT + i] != mobility[i]) {
          disagreements++;
        }
      }
      for (size_t i = 0; i < KING_SAFETY_COUNT; ++i) {
        if (data.king_safety[row * KING_SAFETY_COUNT + i] != safety[i]) {
          disagreements++;
        }
      }
      for (size_t i = 0; i < PASSED_PAWN_COUNT; ++i) {
        if (data.passed_pawn[row * PASSED_PAWN_COUNT + i] != passed[i]) {
          disagreements++;
        }
      }
      for (size_t i = 0; i < PAWN_STRUCTURE_COUNT; ++i) {
        if (data.pawn_structure[row * PAWN_STRUCTURE_COUNT + i] !=
            structure[i]) {
          disagreements++;
        }
      }
      for (size_t i = 0; i < PIECE_PLACEMENT_COUNT; ++i) {
        if (data.piece_placement[row * PIECE_PLACEMENT_COUNT + i] !=
            placement_counts[i]) {
          disagreements++;
        }
      }
      if (data.tempo[row] != tempo) { disagreements++; }

      row++;
    }

    printf("columns: %zu rows re-extracted, %zu disagreements\n", row,
           disagreements);

    if (row != data.size()) {
      printf("columns: FAIL row count %zu against %zu loaded\n", row,
             data.size());
    }
  }

  // ------------------------------------------------------------ identities
  if (opts.identities) {
    size_t rook_rows = 0;
    size_t rook_bad = 0;
    size_t pawn_rows = 0;
    size_t pawn_bad = 0;

    for (size_t row = 0; row < data.size(); ++row) {
      int rook_seventh = 0;
      int pawn_seventh = 0;

      for (uint32_t j = data.offsets[row]; j < data.offsets[row + 1]; ++j) {
        const uint16_t code = data.pieces[j];
        const int sign = (code & eval_model::BLACK_BIT) ? -1 : 1;
        const size_t square = code & ~eval_model::BLACK_BIT;
        const size_t type = square / 64;
        const size_t file_square = square % 64;

        if (file_square < SEVENTH_FIRST || file_square > SEVENTH_LAST) {
          continue;
        }

        if (type == ROOK_TYPE) { rook_seventh += sign; }
        if (type == PAWN_TYPE) { pawn_seventh += sign; }
      }

      const int stored_rook =
          data.piece_placement[row * PIECE_PLACEMENT_COUNT + PL_ROOK_SEVENTH];
      const int stored_pawn = data.passed_pawn[row * PASSED_PAWN_COUNT + 5];

      if (stored_rook != 0 || rook_seventh != 0) { rook_rows++; }
      if (stored_pawn != 0 || pawn_seventh != 0) { pawn_rows++; }

      if (stored_rook != rook_seventh) { rook_bad++; }
      if (stored_pawn != pawn_seventh) { pawn_bad++; }
    }

    printf(
        "identities: rook seventh == signed rook occupancy of squares 8..15: "
        "%zu rows non-zero, %zu violations\n",
        rook_rows, rook_bad);
    printf(
        "identities: passer bucket 5 == signed pawn occupancy of squares "
        "8..15: %zu rows non-zero, %zu violations\n",
        pawn_rows, pawn_bad);
  }

  // ----------------------------------------------------------- occurrence
  if (opts.occurrence) {
    // Seven bands rather than a histogram of 25: the taper is what the bands
    // are about, and phase 0 is its own band because mg_weight is exactly zero
    // there and a middlegame weight gets no gradient at all from those rows.
    struct band_t
    {
      const char* name;
      int lo;
      int hi;
    };

    static const band_t bands[] = {
        {"0", 0, 0},       {"1-4", 1, 4},     {"5-8", 5, 8},    {"9-12", 9, 12},
        {"13-16", 13, 16}, {"17-20", 17, 20}, {"21-24", 21, 24}};
    constexpr size_t BAND_COUNT = sizeof(bands) / sizeof(bands[0]);

    struct column_t
    {
      const char* name;
      const int16_t* base;
      size_t stride;
      size_t index;
    };

    std::vector<column_t> columns;
    static const char* const passer_names[6] = {
        "passer bucket 0", "passer bucket 1", "passer bucket 2",
        "passer bucket 3", "passer bucket 4", "passer bucket 5"};
    static const char* const placement_names[4] = {
        "bishop pair", "rook open", "rook half-open", "rook seventh"};

    for (size_t i = 0; i < PASSED_PAWN_COUNT; ++i) {
      columns.push_back(
          {passer_names[i], data.passed_pawn.data(), PASSED_PAWN_COUNT, i});
    }
    for (size_t i = 0; i < PIECE_PLACEMENT_COUNT; ++i) {
      columns.push_back({placement_names[i], data.piece_placement.data(),
                         PIECE_PLACEMENT_COUNT, i});
    }

    size_t band_rows[BAND_COUNT] = {};
    for (size_t row = 0; row < data.size(); ++row) {
      for (size_t b = 0; b < BAND_COUNT; ++b) {
        if (data.phase[row] >= bands[b].lo && data.phase[row] <= bands[b].hi) {
          band_rows[b]++;
        }
      }
    }

    printf("\noccurrence: percent of rows with a non-zero differential\n");
    printf("%-18s %8s", "column", "all");
    for (size_t b = 0; b < BAND_COUNT; ++b) {
      printf(" %8s", bands[b].name);
    }
    printf("\n");
    printf("%-18s %8.2f", "rows (millions)",
           static_cast<double>(data.size()) / 1e6);
    for (size_t b = 0; b < BAND_COUNT; ++b) {
      printf(" %8.2f", static_cast<double>(band_rows[b]) / 1e6);
    }
    printf("\n");

    for (const column_t& column : columns) {
      size_t all = 0;
      size_t per_band[BAND_COUNT] = {};

      for (size_t row = 0; row < data.size(); ++row) {
        if (column.base[row * column.stride + column.index] == 0) { continue; }

        all++;

        for (size_t b = 0; b < BAND_COUNT; ++b) {
          if (data.phase[row] >= bands[b].lo &&
              data.phase[row] <= bands[b].hi) {
            per_band[b]++;
          }
        }
      }

      printf(
          "%-18s %8.2f", column.name,
          100.0 * static_cast<double>(all) / static_cast<double>(data.size()));
      for (size_t b = 0; b < BAND_COUNT; ++b) {
        const double share = (band_rows[b] > 0)
                                 ? 100.0 * static_cast<double>(per_band[b]) /
                                       static_cast<double>(band_rows[b])
                                 : 0.0;
        printf(" %8.2f", share);
      }
      printf("\n");
    }

    // Tempo is not a count and has no zero case; what it has is a label-side
    // question. Its whole signal is the gap between the mean outcome of rows
    // with White to move and rows with Black to move, so that gap is the thing
    // to report. datagen skips a position whose side to move is in check, which
    // removes rows correlated with the mover standing worse -- a selection the
    // gap below is measured against and not corrected for.
    size_t white_rows = 0;
    size_t black_rows = 0;
    double white_result = 0.0;
    double black_result = 0.0;

    for (size_t row = 0; row < data.size(); ++row) {
      if (data.tempo[row] > 0) {
        white_rows++;
        white_result += data.result[row];
      } else {
        black_rows++;
        black_result += data.result[row];
      }
    }

    printf("\ntempo: %zu rows White to move, mean result %.6f\n", white_rows,
           (white_rows > 0) ? white_result / static_cast<double>(white_rows)
                            : 0.0);
    printf("tempo: %zu rows Black to move, mean result %.6f\n", black_rows,
           (black_rows > 0) ? black_result / static_cast<double>(black_rows)
                            : 0.0);
    printf(
        "tempo: gap %.6f, White relative\n",
        ((white_rows > 0) ? white_result / static_cast<double>(white_rows)
                          : 0.0) -
            ((black_rows > 0) ? black_result / static_cast<double>(black_rows)
                              : 0.0));
  }

  // --------------------------------------------------------- collinearity
  if (opts.collinearity) {
    const size_t stride =
        (data.size() > opts.sample) ? (data.size() / opts.sample) : 1;

    std::vector<uint32_t> rows;
    for (size_t row = 0; row < data.size(); row += stride) {
      rows.push_back(static_cast<uint32_t>(row));
    }

    printf(
        "\ncollinearity: R^2 of a term column on the piece-square columns "
        "it overlaps, %zu rows (every %zuth)\n",
        rows.size(), stride);

    // The types whose tables could absorb the column, which is not always the
    // one type the feature is named after. A rook on an open file is a
    // statement about a rook *and* about the pawns on its file, and both are
    // priced by a table, so the honest question puts 128 columns on the right
    // hand side and not 64. The passer buckets are the opposite case and stay
    // at pawns alone: a passer depends on the enemy pawns ahead of it, and the
    // signed occupancy column cannot separate a White pawn on a square from a
    // Black one mirrored onto it -- which is the point, because the model
    // cannot either. What is being asked throughout is whether the tables *as
    // the fit sees them* can express the column.
    struct target_t
    {
      const char* name;
      std::vector<size_t> psqt_types;
      const int16_t* base;
      size_t stride;
      size_t index;
    };

    std::vector<target_t> targets = {
        {"bishop pair",
         {BISHOP_TYPE},
         data.piece_placement.data(),
         PIECE_PLACEMENT_COUNT,
         PL_BISHOP_PAIR},
        {"rook open",
         {ROOK_TYPE, PAWN_TYPE},
         data.piece_placement.data(),
         PIECE_PLACEMENT_COUNT,
         PL_ROOK_OPEN},
        {"rook half-open",
         {ROOK_TYPE, PAWN_TYPE},
         data.piece_placement.data(),
         PIECE_PLACEMENT_COUNT,
         PL_ROOK_HALF_OPEN},
        {"rook seventh",
         {ROOK_TYPE},
         data.piece_placement.data(),
         PIECE_PLACEMENT_COUNT,
         PL_ROOK_SEVENTH},
    };

    static const char* const passer_names[6] = {
        "passer bucket 0", "passer bucket 1", "passer bucket 2",
        "passer bucket 3", "passer bucket 4", "passer bucket 5"};
    for (size_t i = 0; i < PASSED_PAWN_COUNT; ++i) {
      targets.push_back({passer_names[i],
                         {PAWN_TYPE},
                         data.passed_pawn.data(),
                         PASSED_PAWN_COUNT,
                         i});
    }

    // One occupancy block per piece type, built once and shared.
    std::vector<occupancy_t> occupancy(6);
    for (const target_t& target : targets) {
      for (const size_t type : target.psqt_types) {
        if (occupancy[type].value.empty()) {
          occupancy[type] = occupancy_of_type(data, type, rows);
        }
      }
    }

    for (const target_t& target : targets) {
      std::vector<double> y(rows.size());
      for (size_t r = 0; r < rows.size(); ++r) {
        y[r] = target.base[rows[r] * target.stride + target.index];
      }

      std::vector<std::vector<double>> columns;
      std::string right_hand;

      for (const size_t type : target.psqt_types) {
        const occupancy_t& block = occupancy[type];

        for (size_t square = 0; square < 64; ++square) {
          std::vector<double> column(rows.size());
          for (size_t r = 0; r < rows.size(); ++r) {
            column[r] = block.value[r * 64 + square];
          }
          columns.push_back(std::move(column));
        }

        if (!right_hand.empty()) { right_hand += "+"; }
        right_hand += (type == PAWN_TYPE)     ? "pawn"
                      : (type == BISHOP_TYPE) ? "bishop"
                                              : "rook";
      }

      printf("%-18s R^2 %.6f  on %s psqt, %zu columns\n", target.name,
             r_squared(y, columns), right_hand.c_str(), columns.size());
    }
  }

  // ---------------------------------------------------------------- plant
  //
  // The planted weights. Every one is written here, chosen to be well clear of
  // the rounding lround() applies when a fit is emitted and distinguishable
  // from its neighbours, and derived from nothing outside this repository --
  // their only job is to be a vector a correct fit gets back.
  if (!opts.plant.empty()) {
    std::vector<double> params(PARAM_COUNT, 0.0);
    eval_model::starting_params(params.data());

    static const double planted_passed_mg[6] = {7, 14, 21, 33, 48, 66};
    static const double planted_passed_eg[6] = {11, 19, 30, 45, 70, 95};
    static const double planted_placement_mg[4] = {28, 17, 9, 13};
    static const double planted_placement_eg[4] = {41, 8, 5, 22};
    static const double planted_tempo_mg = 23;
    static const double planted_tempo_eg = 12;

    // Which groups the plant moves, because it decides what a recovery run can
    // prove. `--only GROUP` holds every other parameter at what the engine
    // ships, so a plant that moved three groups and a fit that frees one leaves
    // the freed group absorbing the other two -- a real disagreement with the
    // planted vector that says nothing about the pipeline. Planting one group
    // and fitting exactly that group is the only shape whose prediction is
    // "recovers the planted number", full stop.
    const bool all = (opts.plant_group == "all");
    const bool plant_passed = all || opts.plant_group == "passed_pawns";
    const bool plant_placement = all || opts.plant_group == "piece_placement";
    const bool plant_tempo = all || opts.plant_group == "tempo";

    if (!plant_passed && !plant_placement && !plant_tempo) {
      fprintf(stderr, "unknown --plant-group %s\n", opts.plant_group.c_str());
      return 1;
    }

    if (plant_passed) {
      for (size_t i = 0; i < PASSED_PAWN_COUNT; ++i) {
        params[PP_MG_BASE + i] = planted_passed_mg[i];
        params[PP_EG_BASE + i] = planted_passed_eg[i];
      }
    }
    if (plant_placement) {
      for (size_t i = 0; i < PIECE_PLACEMENT_COUNT; ++i) {
        params[PL_MG_BASE + i] = planted_placement_mg[i];
        params[PL_EG_BASE + i] = planted_placement_eg[i];
      }
    }
    if (plant_tempo) {
      params[TEMPO_MG_BASE] = planted_tempo_mg;
      params[TEMPO_EG_BASE] = planted_tempo_eg;
    }

    printf("\nplant: group %s, K %.6f, labels are sigmoid(K * model score)\n",
           opts.plant_group.c_str(), opts.plant_k);
    // Only what was actually planted is printed. A log naming a weight the run
    // held at zero is a log that cannot be read back as the recovery target.
    if (plant_passed) {
      printf("plant: passed_pawn_mg {%g, %g, %g, %g, %g, %g}\n",
             planted_passed_mg[0], planted_passed_mg[1], planted_passed_mg[2],
             planted_passed_mg[3], planted_passed_mg[4], planted_passed_mg[5]);
      printf("plant: passed_pawn_eg {%g, %g, %g, %g, %g, %g}\n",
             planted_passed_eg[0], planted_passed_eg[1], planted_passed_eg[2],
             planted_passed_eg[3], planted_passed_eg[4], planted_passed_eg[5]);
    }
    if (plant_placement) {
      printf("plant: piece_placement_mg {%g, %g, %g, %g}\n",
             planted_placement_mg[0], planted_placement_mg[1],
             planted_placement_mg[2], planted_placement_mg[3]);
      printf("plant: piece_placement_eg {%g, %g, %g, %g}\n",
             planted_placement_eg[0], planted_placement_eg[1],
             planted_placement_eg[2], planted_placement_eg[3]);
    }
    if (plant_tempo) {
      printf("plant: tempo_mg %g, tempo_eg %g\n", planted_tempo_mg,
             planted_tempo_eg);
    }
    printf("plant: every other parameter is what the engine ships\n");

    // The FEN, the score and the phase are copied through verbatim so that only
    // the label differs: a synthetic corpus whose features moved would be
    // testing two things at once.
    std::ifstream in(opts.data);
    std::ofstream out(opts.plant);

    if (!out) {
      fprintf(stderr, "could not write %s\n", opts.plant.c_str());
      return 1;
    }

    std::string line;
    size_t row = 0;
    size_t written = 0;

    while (std::getline(in, line)) {
      if (line.empty()) { continue; }

      std::istringstream fields(line);
      std::string fen, result_text, score_text, phase_text;
      std::getline(fields, fen, '\t');
      std::getline(fields, result_text, '\t');
      std::getline(fields, score_text, '\t');
      std::getline(fields, phase_text, '\t');

      const double score =
          tuner_model::evaluate_position(data, row, params.data());
      const double label = tuner_target::sigmoid(score, opts.plant_k);

      out << fen << '\t' << label << '\t' << score_text << '\t' << phase_text
          << '\n';

      row++;
      written++;
    }

    printf("plant: %zu rows written to %s\n", written, opts.plant.c_str());
  }

  return 0;
}
