#pragma once
// The label the tuner fits against, and why it is a blend of two of them. S075.
//
// `tools/datagen.cpp` writes `fen result score phase` and the tuner read two of
// those columns. `score` is the engine's own score for the position at the
// datagen node budget, White relative, and this header is what finally reads
// it:
//
//   target = lambda * sigma(K * score) + (1 - lambda) * result
//
// `adocs/eval_tuning_strategy.md` section 2.7 is the argument for it. The game
// result is unbiased and very high variance -- one noisy bit spread over about
// 92 positions of one game, every one of them carrying the same label whatever
// happened on the board afterwards. The search score is low variance and biased
// toward the evaluator that produced it. The blend is reported to beat either
// alone, for a hand-crafted evaluation and not only for a network.
//
// `lambda` 0 is the target the tuner used before this header existed, and that
// path is bit for bit what it was: `0.0 * sigma + 1.0 * result` is `result`.
//
// **The hazard is stated in section 1 of the same document and it is not
// hypothetical.** Fitting an evaluation toward its own search at the same depth
// is a fixed point that carries no information. What keeps `lambda` 1 from
// being exactly that here is one thing only: the scores in
// `.tuning/selfplay_v2.tsv` were produced by the engine of 2026-08-14, before
// S065 moved 827 constants, so they are not the current evaluator's own output.
// The mitigation expires the moment a corpus is regenerated by the engine being
// fitted, which S082 and S083 both do. Whoever runs a fit at a non-zero lambda
// states the corpus's generating commit beside it.
//
// Two consequences follow from the target depending on both K and lambda, and
// both are DEC-064:
//
//   - **K is fitted against the game result alone, and then held.** It is the
//     scale that turns a centipawn into a win probability, so it belongs to the
//     data rather than to the objective. A K fitted against a target that
//     contains K chases itself, and two lambda runs would not share a scale.
//   - **Held-out error against the game result is what selects lambda**, never
//     the training objective. Each lambda trains against a different target, so
//     two runs' training errors are not comparable numbers at all: the blend at
//     lambda 1 is a smooth function of a column the game result knows nothing
//     about, and a lower error against it means only that the fit found the old
//     search easier to predict than the outcome. At lambda 0 the two metrics
//     are the same function, which is what keeps that path unchanged.
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <string>

namespace tuner_target
{

// The scale the tuner has always converted a centipawn score with: 400
// centipawns is a factor of ten in the odds, which is the Elo convention the
// sigmoid inherits. Lives here rather than in tuner.cpp so that the fitted
// sigmoid and the one the target is built from cannot drift apart.
constexpr double LN10_OVER_400 = 2.302585092994046 / 400.0;


// The win probability a centipawn score maps to at scale `k`. Used twice per
// row and for two different things: on an evaluation it is the prediction the
// fit is scored on, and on the `score` column it is the search's own opinion
// turned into the same units as the game result.
inline double sigmoid(double score, double k)
{ return 1.0 / (1.0 + std::exp(-k * score * LN10_OVER_400)); }


// The blended label. At `lambda` 0 this returns `result` bit for bit -- the
// first term is exactly 0.0 and the second is exactly `result` -- which is what
// makes the pre-S075 fit reproducible rather than merely close.
inline double blend(double lambda, double score, double result, double k)
{ return lambda * sigmoid(score, k) + (1.0 - lambda) * result; }


// A lambda outside [0, 1] is not a blend of anything, and a NaN fails both
// comparisons rather than passing one of them, which is why this is written as
// two `>=`/`<=` tests and not as a negated range.
inline bool valid_lambda(double lambda)
{ return lambda >= 0.0 && lambda <= 1.0; }


// The `score` column of one `fen result score phase` row, strictly parsed.
// False when the field is empty, is not an integer, carries trailing text, or
// does not fit the int16 the dataset stores it in.
//
// Strict because the column has never been read before: every existing corpus
// was written by datagen, which bounds it by `--quiet-limit` and produced
// -999 .. 999 over all 11003693 rows of `selfplay_v2.tsv`, but nothing in the
// format says so, and `atoi` answers 0 for a field it cannot parse. A label
// silently defaulting to "the position is equal" is the failure this refuses.
inline bool parse_score(const std::string& field, int* score)
{
  if (field.empty()) { return false; }

  char* end = nullptr;
  const long value = std::strtol(field.c_str(), &end, 10);

  if (end == field.c_str() || *end != '\0') { return false; }
  if (value < -32768 || value > 32767) { return false; }

  *score = static_cast<int>(value);
  return true;
}

}  // namespace tuner_target
