# S077, extended by S212. Writes what this build is into a generated header:
# the commit it was compiled from, the instruction set it targets and whether
# it is the tune build. An emitted weight table names the commit (S077) and
# `id name` carries all three (S212).
#
# Run as a script (`cmake -P`) by a custom target on every build, not at
# configure time. Configure time is the trap this avoids: `cmake -S . -B build`
# runs once and a sha captured there goes stale on the next commit, so a table
# would carry a commit that is not the one its binary was built from -- worse
# than carrying none, because it reads as provenance. It is worse still for
# `id name`, where `fastchess.sh` refuses a run whose engine answers a sha
# other than the one it labelled that side with: a stamp that goes stale
# between a commit and a rebuild would refuse a run that is perfectly good.
#
# It rewrites the file only when the content changes, so a translation unit
# that includes it recompiles when the value moves and not on every build.
#
# `-dirty` follows `fastchess.sh` and the run scripts under `adocs/data/`:
# `git diff --quiet` over tracked files. An untracked file is not counted, on
# the same convention -- `adocs/` and `.tuning/` carry untracked evidence
# constantly and none of it compiles into anything.
#
# The short sha comes from `git rev-parse --short` and not from
# `git describe --always --dirty`: this repository carries nine tags from the
# pre-`achesso` history, so `describe` answers `v0.3.0-520-g47be85b`, which is
# not a short sha and does not compare against the `git rev-parse --short` that
# `fastchess.sh` labels each side with. The value wanted is the abbreviation
# both ends produce. S212.

set(sha "unknown")

# ARCH and TUNE are configure-time facts and reach the script on its command
# line; the commit is the only thing read here. A missing ARCH is `unknown`
# rather than a guess at cmake/arch.cmake's default, which would be a claim
# about a binary this script cannot see.
if(NOT DEFINED ARCH OR ARCH STREQUAL "")
     set(ARCH "unknown")
endif()

# A leading space, so the C++ side is a string-literal concatenation with
# nothing to test at run time.
set(tune "")

if(TUNE)
     set(tune " tune")
endif()

execute_process(
     COMMAND git -C ${SOURCE_DIR} rev-parse --short HEAD
     OUTPUT_VARIABLE head_sha
     OUTPUT_STRIP_TRAILING_WHITESPACE
     RESULT_VARIABLE sha_status
     ERROR_QUIET)

if(sha_status EQUAL 0)
     set(sha "${head_sha}")

     execute_process(
          COMMAND git -C ${SOURCE_DIR} diff --quiet HEAD
          RESULT_VARIABLE dirty_status
          ERROR_QUIET)

     if(NOT dirty_status EQUAL 0)
          set(sha "${sha}-dirty")
     endif()
endif()

set(content "#pragma once
// Generated by cmake/build_info.cmake on every build. Do not edit and do not
// track: the values are properties of the build, not of the source. S077, S212.
#define CHESSO_BUILD_COMMIT \"${sha}\"
#define CHESSO_BUILD_ARCH \"${ARCH}\"
// Empty in every build but the tune one, where it is \" tune\" -- a leading
// space, so `id name` concatenates it as a literal.
#define CHESSO_BUILD_TUNE \"${tune}\"
")

set(existing "")

if(EXISTS ${OUTPUT})
     file(READ ${OUTPUT} existing)
endif()

if(NOT existing STREQUAL content)
     file(WRITE ${OUTPUT} "${content}")
endif()
