# S077. Writes the commit the tuner is built from into a generated header, so
# an emitted weight table can name it.
#
# Run as a script (`cmake -P`) by a custom target on every build, not at
# configure time. Configure time is the trap this avoids: `cmake -S . -B build`
# runs once and a sha captured there goes stale on the next commit, so a table
# would carry a commit that is not the one its binary was built from -- worse
# than carrying none, because it reads as provenance.
#
# It rewrites the file only when the content changes, so the tuner recompiles
# when the commit moves and not on every build.
#
# `-dirty` follows `fastchess.sh` and the run scripts under `adocs/data/`:
# `git diff --quiet` over tracked files. An untracked file is not counted, on
# the same convention -- `adocs/` and `.tuning/` carry untracked evidence
# constantly and none of it compiles into anything.

set(sha "unknown")

execute_process(
     COMMAND git -C ${SOURCE_DIR} rev-parse --short HEAD
     OUTPUT_VARIABLE head_sha
     OUTPUT_STRIP_TRAILING_WHITESPACE
     RESULT_VARIABLE sha_status
     ERROR_QUIET)

if(sha_status EQUAL 0)
     set(sha "${head_sha}")

     execute_process(
          COMMAND git -C ${SOURCE_DIR} diff --quiet HEAD
          RESULT_VARIABLE dirty_status
          ERROR_QUIET)

     if(NOT dirty_status EQUAL 0)
          set(sha "${sha}-dirty")
     endif()
endif()

set(content "#pragma once
// Generated by cmake/build_info.cmake on every build. Do not edit and do not
// track: the value is a property of the build, not of the source. S077.
#define CHESSO_BUILD_COMMIT \"${sha}\"
")

set(existing "")

if(EXISTS ${OUTPUT})
     file(READ ${OUTPUT} existing)
endif()

if(NOT existing STREQUAL content)
     file(WRITE ${OUTPUT} "${content}")
endif()
